In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv(r"C:\Users\AARATHI R NAIR\Downloads\titanic_dataset.csv")

In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df.shape

(891, 12)

In [5]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [6]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [7]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [8]:
df.drop('Name',axis=1,inplace=True)
df.drop('Cabin',axis=1,inplace=True)
df.dropna(inplace=True)

In [9]:
df['Age']=df['Age'].fillna(df['Age'].mean)

In [10]:
df['Embarked'].mode()[0]

'S'

In [11]:
df['Age']=df['Age'].fillna(df['Embarked'].mode()[0])

In [12]:
df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [14]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked        object
dtype: object

In [24]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Sex']=le.fit_transform(df['Sex'])
df['Ticket']=le.fit_transform(df['Ticket'])
df['Embarked']=le.fit_transform(df['Embarked'])
df.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch  Ticket     Fare  \
0            1         0       3    1  22.0      1      0     407   7.2500   
1            2         1       1    0  38.0      1      0     470  71.2833   
2            3         1       3    0  26.0      0      0     531   7.9250   
3            4         1       1    0  35.0      1      0      39  53.1000   
4            5         0       3    1  35.0      0      0     372   8.0500   

   Embarked  
0         2  
1         0  
2         2  
3         2  
4         2

In [25]:
x=df.drop('Survived',axis=1)
y=df['Survived']

In [26]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [27]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score

# KNN

In [28]:
from sklearn.neighbors import KNeighborsClassifier
k_metrics=[]
neighbor=np.arange(3,15)
for k in neighbor:
    knn=KNeighborsClassifier(n_neighbors=k,metric='euclidean')
    knn.fit(x_train,y_train)
    y_predict=knn.predict(x_test)
    acc=accuracy_score(y_test,y_predict)
    k_metrics.append(acc)
    
k_metrics

[0.6433566433566433,
 0.6153846153846154,
 0.6293706293706294,
 0.6503496503496503,
 0.6293706293706294,
 0.6713286713286714,
 0.6433566433566433,
 0.6713286713286714,
 0.6783216783216783,
 0.6503496503496503,
 0.6643356643356644,
 0.6643356643356644]

# SVM

In [29]:
from sklearn.svm import SVC


In [30]:
svm_cls=SVC(kernel='linear')
svm_cls=svm_cls.fit(x_train,y_train)
y_pred_svm=svm_cls.predict(x_test)

In [31]:
confusion_matrix(y_test,y_pred_svm)

array([[68, 12],
       [24, 39]], dtype=int64)

In [32]:
print('Accuracy=',accuracy_score(y_test,y_pred_svm))
print('Precision=',precision_score(y_test,y_pred_svm))
print('recall=',recall_score(y_test,y_pred_svm))
print('f1=',f1_score(y_test,y_pred_svm))

Accuracy= 0.7482517482517482
Precision= 0.7647058823529411
recall= 0.6190476190476191
f1= 0.6842105263157895


# K-FOLD

In [33]:
from sklearn.model_selection import KFold
kfold_Validator=KFold(10)
for train_index,test_index in kfold_Validator.split(x,y):
    print('Training Index:',train_index)
    print('Testing Index:',test_index)

Training Index: [ 72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 31

In [34]:
from sklearn.model_selection import cross_val_score
cv_result=cross_val_score(svm_cls,x,y,cv=kfold_Validator)

In [35]:
cv_result

array([0.80555556, 0.79166667, 0.74647887, 0.83098592, 0.71830986,
       0.77464789, 0.71830986, 0.73239437, 0.8028169 , 0.8028169 ])

In [36]:
np.mean(cv_result)

0.7723982785602506

# Stratified Cross Validation

In [37]:
from sklearn.model_selection import StratifiedKFold
skfold_validator=StratifiedKFold(n_splits=10)

In [38]:
for train_index,test_index in skfold_validator.split(x,y):
    print('Training Index:',train_index)
    print('Testing Index:',test_index)


Training Index: [ 71  72  73  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 31

In [39]:
cv_result=cross_val_score(svm_cls,x,y,cv=skfold_validator)

In [40]:
cv_result

array([0.79166667, 0.76388889, 0.78873239, 0.84507042, 0.71830986,
       0.77464789, 0.74647887, 0.73239437, 0.83098592, 0.77464789])

In [41]:
np.mean(cv_result) 

0.7766823161189359